updated

diff --git a/.github/workflows/first.yaml b/.github/workflows/first.yaml
--- a/.github/workflows/first.yaml
+++ b/.github/workflows/first.yaml
@@ -17,8 +17,8 @@ jobs:
           echo "Step 3"
           echo "Step 4"
 
-      - name: Force failure
-        run: exit 1
+    ##  - name: Force failure
+    ##   run: exit 1
 
       - name: Send email on failure
         if: failure()
